version: 0.0
os: linux
files:
  - source: /target/hello-app.war
    destination: /var/lib/tomcat8/webapps
hooks:
 ApplicationStop:
   - location: scripts/stop_server.sh
     timeout: 300
     runas: root
 BeforeInstall:
   - location: scripts/install_dependencies.sh
     timeout: 300
     runas: root
 ApplicationStart:
   - location: scripts/start_server.sh
     timeout: 300
     runas: root
 ValidateService:
    - location: scripts/health_check.sh
